import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { alertsAPI } from '../../services/api';

const SEV_ICONS = { CRITICAL: '🔴', HIGH: '🟠', MODERATE: '🟡', LOW: '🟢' };

export default function PublicAlerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    alertsAPI.getAll({ status: 'NEW' }).then(res => {
      if (res.success) setAlerts(res.data.filter(a => a.status !== 'RESOLVED').slice(0, 10));
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="loading-spinner"><div className="spinner" /></div>;

  return (
    <div style={{ padding: '48px 0' }}>
      <div className="container">
        <div className="page-header">
          <h1 className="page-title">⚠️ Safety & Conservation Alerts</h1>
          <p className="page-subtitle">Active alerts from the HeritageGuard AI monitoring system</p>
        </div>

        <div className="alert-banner warning mb-20">
          ⚠️ These alerts are generated by AI agents based on simulated sensor and visitor data. Always follow official site instructions.
        </div>

        {alerts.length === 0 ? (
          <div className="card" style={{ padding: 40, textAlign: 'center', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>✅</div>
            <p>No active alerts at this time. All sites are within normal parameters.</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {alerts.map(alert => (
              <div key={alert.id} className="card">
                <div className="card-body">
                  <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                    <span style={{ fontSize: 22, marginTop: 2 }}>{SEV_ICONS[alert.severity] || '⚠️'}</span>
                    <div style={{ flex: 1 }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginBottom: 6 }}>
                        <div style={{ fontWeight: 700, fontSize: 15 }}>{alert.title || alert.description}</div>
                        <div style={{ display: 'flex', gap: 8 }}>
                          <span className={`badge badge-${alert.severity.toLowerCase()}`}>{alert.severity}</span>
                          <span className={`badge badge-${alert.status.toLowerCase()}`}>{alert.status}</span>
                        </div>
                      </div>
                      <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 6 }}>
                        📍 {alert.site} · 🤖 {alert.agent} · 🕐 {new Date(alert.time).toLocaleString('en-IN')}
                      </div>
                      <p style={{ fontSize: 14, color: 'var(--text-secondary)', marginBottom: 8 }}>{alert.description}</p>
                      {alert.aiRecommendation && (
                        <div style={{ padding: '8px 12px', background: 'var(--bg-secondary)', borderRadius: 6, borderLeft: '3px solid var(--heritage-gold)', fontSize: 13, color: 'var(--text-secondary)' }}>
                          💡 <strong>AI Recommendation:</strong> {alert.aiRecommendation}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        <div style={{ marginTop: 24, display: 'flex', gap: 12 }}>
          <Link to="/dashboard/alerts" className="btn btn-dark">📊 Full Alert Dashboard</Link>
          <Link to="/explore" className="btn btn-secondary">← Back to Explore</Link>
        </div>
      </div>
    </div>
  );
}
